### ISSUE TITLE
SNOHelper<T>.LoadFile() Throws Exception

### ISSUE THREAD

**Issue by tehmufifnman** [Enigma32/Enigma.D3#10]
Reproduction steps:
var snoFile = SNOHelper.LoadFile<StringList>(path_to_file);
[exception thrown]

I've traced it myself some.  At the top MemoryReader.Read is throwing a new Argument exception here on line 59:
```csharp
if (!IsValidAddress(address + TypeHelper<T>.SizeOf))
	throw new ArgumentException("address");
```

Digging further, the issue originates in TypeHelper.SizeOf() method.
```csharp
var field = type.GetField("SizeOf",
	BindingFlags.FlattenHierarchy |
	BindingFlags.Static |
	BindingFlags.Public);
```
That bit of code is not actually finding SizeOf field in the StringList class, because StringList was a generic argument used to run the LoadFile() method above.

This is SUPER hacky and obviously needs to be cleaned up, but in situations where you have a generic argument this finds it, I am just not sure how it works in the greater logic of your code (yet! 😄)

```csharp
var generic = type.GetGenericArguments();
var field = generic[0].GetField("SizeOf");
```

**Comment by Enigma32** [comment]
Thanks for the red herring :) A callstack would have been better. Could not understand why size of StringList would even be needed by the call.

The problem was created when I needed to support both 32-bit and 64-bit. I could then no longer use constants to define the size for different types anymore, since they would vary based on the bitness. So... the solution was to look for a SizeOf const, and if none found return -1. It seemed like a good value as it's typically used when something is not found, and it looks weird enough to raise suspicion :) So if it's -1, then try find a field or property called SizeOf instead. But if there is none of that either, size is still -1 and returned like that.

SNOFile<T> does not have a SizeOf const/field/property defined, so its size is returned as -1. When performing a read, the intention of
```
if (!IsValidAddress(address + TypeHelper<T>.SizeOf))
	throw new ArgumentException("address");
```
is to make sure the last byte is contained in the memory, and therefore probably all bytes. SNOHelper has loaded the file into a buffer, and the SNOFile starts at location 0. Since size is -1, it tries to verify that the end address -1 is contained in the memory :S This does not go very well and you get an exception.

I will change -1 to 0 for when no SizeOf can be found.

**Comment by tehmufifnman** [comment]
Oh man, I have been a developer a long time and I know better than to not include a stack trace.  I had it copied to Notepad++ and everything and just totally forgot to post it!

My apologies and sorry for the red herring :)
