### ISSUE TITLE
Exceptions @Enigma.D3.MemoryModel.Core.AttributeReader.GetAttributeValue(Int32 groupId, AttributeId attributeId, Int32 modifier)

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#20]
I get some Exceptions when reading AttributeValues
```
bei Enigma.D3.MemoryModel.Collections.Vector`1.get_Item(Int32 index)
   bei Enigma.D3.MemoryModel.Collections.Map`2.TryGetValue(TKey key, TValue& value)
   bei Enigma.D3.MemoryModel.Core.AttributeReader.TryGetAttributeValue(Int32 groupId, AttributeId attribId, Int32 modifier, AttributeValue& value)
   bei Enigma.D3.MemoryModel.Core.AttributeReader.GetAttributeValue(Int32 groupId, AttributeId attributeId, Int32 modifier)
```
The Exceptionmessage is in german. It means something like "The argument is out of valid range"

Here are some AttributeIds i try to read.
2017-07-18 00:06:32,6114	Exception Reading AttributeId : SummonedByACDID
2017-07-18 00:06:34,6996	Exception Reading AttributeId : SummonedByACDID
2017-07-18 00:06:35,4722	Exception Reading AttributeId : SummonedByACDID
2017-07-18 00:06:40,5394	Exception Reading AttributeId : HitpointsCur
2017-07-18 00:06:40,5399	Exception Reading AttributeId : HitpointsMax
2017-07-18 00:06:40,5404	Exception Reading AttributeId : HitpointsCur
2017-07-18 00:06:40,5409	Exception Reading AttributeId : HitpointsMax
2017-07-18 00:06:40,5419	Exception Reading AttributeId : HitpointsCur
2017-07-18 00:06:40,5419	Exception Reading AttributeId : HitpointsMax

Can it be a problem with missing locks? since my application using threads.

**Comment by Enigma32** [comment]
So I guess it's on this line https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.MemoryModel/Collections/Vector.cs#L20
Maybe you can break there and see what **index** and **Count** is when it happens.

Does it only happen for those mentioned attributes or is it random? Intermittent exceptions are expected due to race conditions, as D3 isn't waiting for us to read.

**Comment by d2k2-git** [comment]
It happens with random attributes . i guess when monsters are killed fast and acd is not anymore in the memory? i will test more tomorrow. 

can you explain TakeSnapshot() and FreeSnapshot()? Could that help?

**Comment by Enigma32** [comment]
Let's take an ACD as example. In 64-bit, the size is 0x3A0 bytes. If we call TakeSnapshot(), it will read 0x3A0 bytes into a buffer and use that for subsequent reads on the object (e.g. accessing properties) until we call FreeSnapshot(). This reduces chance for race conditions and also improves CPU performance. It doesn't work easily with attribute reading since there are a bunch of pointers involved.

**Comment by d2k2-git** [comment]
I will just catch the Exception and not log it. I still kept the calls to TakeSnapshot() to reduce the chance of Exceptions.
